// <auto-generated />
namespace WcfService1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_employee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_employee));
        
        string IMigrationMetadata.Id
        {
            get { return "202202240249343_add_employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
